name: Créer un APK ForgeKit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installer les dépendances
        run: npm install

      - name: Ajouter la plateforme Android
        run: npx cap add android

      - name: Synchroniser Android
        run: npx cap sync android

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Construire l'APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Récupérer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: ForgeKit-Offline-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
